// src/db/client.ts — Drizzle client factories over the postgres.js driver.
//
// Two TIERS, kept strictly separate (DEC-0010 / threat T-00-09):
//   * BROWSER-SAFE (this file): anon / user-session client. Runs RLS-scoped queries with the
//     user's JWT. Safe to import from anywhere (RSC, route handlers, client components that need
//     types). It NEVER holds the service-role key.
//   * SERVER-ONLY service-role client lives in `./client.server.ts`, guarded by `import 'server-only'`
//     so it can NEVER be bundled into browser code. Import it only from Edge Functions / Route
//     Handlers / Hermes. Do NOT re-export it from here, or the server-only guard would be defeated.
//
// Schema types come from `./schema` (GENERATED by `drizzle-kit pull` — do not hand-edit).

import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';

import * as schema from './schema';

export type AnchorDb = ReturnType<typeof drizzle<typeof schema>>;

/**
 * Browser-safe / user-session Drizzle client.
 *
 * Pass a connection string that authenticates as the anon role (or a per-request user-scoped
 * connection); RLS (`auth.uid() = anchor_user_id`) scopes every read. This factory must never be
 * handed the service-role connection string — that belongs to {@link ./client.server}.
 *
 * @param connectionString postgres:// URL for the anon / user-session role.
 */
export function createUserDb(connectionString: string): AnchorDb {
  const sql = postgres(connectionString, { prepare: false });
  return drizzle(sql, { schema });
}
