// GENERATED by `drizzle-kit pull` — relational mappings for the Drizzle query API.
// SQL migrations are the source of truth (DEC-0013); re-run the pull after schema changes.
import { relations } from "drizzle-orm/relations";
import { anchorUser, pairingCode, conversationTranscript, sourceEvidence, memoryFact, memoryEntity, memoryRelationship, diaryEntry, calendarEvent, memoryIndexItem, trustedContact, telegramSession, auditEvent, agentCostLog, usersInAuth, anchorUserPlan, googleConnection } from "./schema";

export const pairingCodeRelations = relations(pairingCode, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [pairingCode.anchorUserId],
		references: [anchorUser.id]
	}),
}));

export const anchorUserRelations = relations(anchorUser, ({one, many}) => ({
	pairingCodes: many(pairingCode),
	conversationTranscripts: many(conversationTranscript),
	sourceEvidences: many(sourceEvidence),
	memoryFacts: many(memoryFact),
	memoryEntities: many(memoryEntity),
	memoryRelationships: many(memoryRelationship),
	diaryEntries: many(diaryEntry),
	calendarEvents: many(calendarEvent),
	memoryIndexItems: many(memoryIndexItem),
	trustedContacts: many(trustedContact),
	telegramSessions: many(telegramSession),
	auditEvents: many(auditEvent),
	agentCostLogs: many(agentCostLog),
	usersInAuth: one(usersInAuth, {
		fields: [anchorUser.id],
		references: [usersInAuth.id]
	}),
	anchorUserPlans: many(anchorUserPlan),
	googleConnections: many(googleConnection),
}));

export const conversationTranscriptRelations = relations(conversationTranscript, ({one, many}) => ({
	anchorUser: one(anchorUser, {
		fields: [conversationTranscript.anchorUserId],
		references: [anchorUser.id]
	}),
	sourceEvidences: many(sourceEvidence),
	memoryIndexItems: many(memoryIndexItem),
}));

export const sourceEvidenceRelations = relations(sourceEvidence, ({one, many}) => ({
	anchorUser: one(anchorUser, {
		fields: [sourceEvidence.anchorUserId],
		references: [anchorUser.id]
	}),
	conversationTranscript: one(conversationTranscript, {
		fields: [sourceEvidence.conversationTranscriptId],
		references: [conversationTranscript.id]
	}),
	memoryFacts: many(memoryFact),
}));

export const memoryFactRelations = relations(memoryFact, ({one, many}) => ({
	anchorUser: one(anchorUser, {
		fields: [memoryFact.anchorUserId],
		references: [anchorUser.id]
	}),
	sourceEvidence: one(sourceEvidence, {
		fields: [memoryFact.sourceEvidenceId],
		references: [sourceEvidence.id]
	}),
	memoryFact: one(memoryFact, {
		fields: [memoryFact.supersededBy],
		references: [memoryFact.id],
		relationName: "memoryFact_supersededBy_memoryFact_id"
	}),
	memoryFacts: many(memoryFact, {
		relationName: "memoryFact_supersededBy_memoryFact_id"
	}),
	memoryIndexItems: many(memoryIndexItem),
}));

export const memoryEntityRelations = relations(memoryEntity, ({one, many}) => ({
	anchorUser: one(anchorUser, {
		fields: [memoryEntity.anchorUserId],
		references: [anchorUser.id]
	}),
	memoryRelationships_fromEntityId: many(memoryRelationship, {
		relationName: "memoryRelationship_fromEntityId_memoryEntity_id"
	}),
	memoryRelationships_toEntityId: many(memoryRelationship, {
		relationName: "memoryRelationship_toEntityId_memoryEntity_id"
	}),
}));

export const memoryRelationshipRelations = relations(memoryRelationship, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [memoryRelationship.anchorUserId],
		references: [anchorUser.id]
	}),
	memoryEntity_fromEntityId: one(memoryEntity, {
		fields: [memoryRelationship.fromEntityId],
		references: [memoryEntity.id],
		relationName: "memoryRelationship_fromEntityId_memoryEntity_id"
	}),
	memoryEntity_toEntityId: one(memoryEntity, {
		fields: [memoryRelationship.toEntityId],
		references: [memoryEntity.id],
		relationName: "memoryRelationship_toEntityId_memoryEntity_id"
	}),
}));

export const diaryEntryRelations = relations(diaryEntry, ({one, many}) => ({
	anchorUser: one(anchorUser, {
		fields: [diaryEntry.anchorUserId],
		references: [anchorUser.id]
	}),
	memoryIndexItems: many(memoryIndexItem),
}));

export const calendarEventRelations = relations(calendarEvent, ({one, many}) => ({
	anchorUser: one(anchorUser, {
		fields: [calendarEvent.anchorUserId],
		references: [anchorUser.id]
	}),
	memoryIndexItems: many(memoryIndexItem),
}));

export const memoryIndexItemRelations = relations(memoryIndexItem, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [memoryIndexItem.anchorUserId],
		references: [anchorUser.id]
	}),
	conversationTranscript: one(conversationTranscript, {
		fields: [memoryIndexItem.conversationTranscriptId],
		references: [conversationTranscript.id]
	}),
	diaryEntry: one(diaryEntry, {
		fields: [memoryIndexItem.diaryEntryId],
		references: [diaryEntry.id]
	}),
	memoryFact: one(memoryFact, {
		fields: [memoryIndexItem.memoryFactId],
		references: [memoryFact.id]
	}),
	calendarEvent: one(calendarEvent, {
		fields: [memoryIndexItem.calendarEventId],
		references: [calendarEvent.id]
	}),
}));

export const trustedContactRelations = relations(trustedContact, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [trustedContact.anchorUserId],
		references: [anchorUser.id]
	}),
}));

export const telegramSessionRelations = relations(telegramSession, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [telegramSession.anchorUserId],
		references: [anchorUser.id]
	}),
}));

export const auditEventRelations = relations(auditEvent, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [auditEvent.anchorUserId],
		references: [anchorUser.id]
	}),
}));

export const agentCostLogRelations = relations(agentCostLog, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [agentCostLog.anchorUserId],
		references: [anchorUser.id]
	}),
}));

export const usersInAuthRelations = relations(usersInAuth, ({many}) => ({
	anchorUsers: many(anchorUser),
}));

export const anchorUserPlanRelations = relations(anchorUserPlan, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [anchorUserPlan.anchorUserId],
		references: [anchorUser.id]
	}),
}));

export const googleConnectionRelations = relations(googleConnection, ({one}) => ({
	anchorUser: one(anchorUser, {
		fields: [googleConnection.anchorUserId],
		references: [anchorUser.id]
	}),
}));