// GENERATED by drizzle-kit pull — do not hand-edit.
//
// This file is OVERWRITTEN by `pnpm drizzle-kit pull` alongside src/db/schema.ts; it holds the
// Drizzle `relations()` definitions introspected from the live foreign keys. The SQL migrations are
// the source of truth (DEC-0013 / Pitfall 2). Never author relations here.
//
// Placeholder until the schema-freeze apply + pull runs (plan 00-03, Task 3).

export {};
