// GENERATED by `drizzle-kit pull` from supabase/migrations/*.sql — the SQL is the source of truth (DEC-0013).
// Do NOT hand-edit table/column definitions; re-run `pnpm drizzle-kit pull` after migrations change.
// Manual bridge only: the `usersInAuth` stub below. drizzle-kit's schemaFilter:['public'] omits the `auth`
// schema, but anchor_user.id FKs to auth.users(id) — the stub lets that cross-schema relation type-resolve.
import { pgTable, pgSchema, index, foreignKey, pgPolicy, text, uuid, timestamp, jsonb, real, date, unique, check, vector, bigint, integer, numeric, boolean, pgEnum, customType } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

const authSchema = pgSchema("auth")

// drizzle-kit pull cannot map tsvector/bytea — declared as custom types here (SQL stays the source of truth).
const tsvector = customType<{ data: string }>({ dataType() { return "tsvector" } })
const bytea = customType<{ data: Uint8Array }>({ dataType() { return "bytea" } })
export const usersInAuth = authSchema.table("users", {
	id: uuid().primaryKey().notNull(),
})

export const googleConnectionState = pgEnum("google_connection_state", ['connected', 'disconnected_external', 'revoked'])
export const memorySourceKind = pgEnum("memory_source_kind", ['conversation_transcript', 'diary_entry', 'memory_fact', 'calendar_event'])
export const trustedContactState = pgEnum("trusted_contact_state", ['pending', 'verified', 'revoked'])


export const pairingCode = pgTable("pairing_code", {
	code: text().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }).notNull(),
	consumedAt: timestamp("consumed_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("pairing_code_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "pairing_code_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("pairing_code_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("pairing_code_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("pairing_code_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("pairing_code_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const conversationTranscript = pgTable("conversation_transcript", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	channel: text().default('telegram').notNull(),
	content: text(),
	metadata: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("conversation_transcript_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("timestamptz_ops"), table.occurredAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "conversation_transcript_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("conversation_transcript_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("conversation_transcript_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("conversation_transcript_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("conversation_transcript_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const sourceEvidence = pgTable("source_evidence", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	conversationTranscriptId: uuid("conversation_transcript_id"),
	excerpt: text().notNull(),
	span: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("source_evidence_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	index("source_evidence_transcript_idx").using("btree", table.conversationTranscriptId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "source_evidence_anchor_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.conversationTranscriptId],
			foreignColumns: [conversationTranscript.id],
			name: "source_evidence_conversation_transcript_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("source_evidence_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("source_evidence_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("source_evidence_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("source_evidence_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const memoryFact = pgTable("memory_fact", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	content: text().notNull(),
	factType: text("fact_type"),
	confidence: real(),
	sourceEvidenceId: uuid("source_evidence_id"),
	supersededBy: uuid("superseded_by"),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'string' }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
	// TODO: failed to parse database type 'tsvector'
	contentTsv: tsvector("content_tsv"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("memory_fact_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	index("memory_fact_content_tsv_idx").using("gin", table.contentTsv.asc().nullsLast().op("tsvector_ops")),
	index("memory_fact_superseded_by_idx").using("btree", table.supersededBy.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "memory_fact_anchor_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.sourceEvidenceId],
			foreignColumns: [sourceEvidence.id],
			name: "memory_fact_source_evidence_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.supersededBy],
			foreignColumns: [table.id],
			name: "memory_fact_superseded_by_fkey"
		}).onDelete("set null"),
	pgPolicy("memory_fact_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("memory_fact_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("memory_fact_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("memory_fact_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const memoryEntity = pgTable("memory_entity", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	entityType: text("entity_type").notNull(),
	displayName: text("display_name").notNull(),
	attributes: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("memory_entity_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "memory_entity_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("memory_entity_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("memory_entity_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("memory_entity_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("memory_entity_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const memoryRelationship = pgTable("memory_relationship", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	fromEntityId: uuid("from_entity_id").notNull(),
	toEntityId: uuid("to_entity_id").notNull(),
	relationshipType: text("relationship_type").notNull(),
	attributes: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("memory_relationship_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	index("memory_relationship_from_entity_idx").using("btree", table.fromEntityId.asc().nullsLast().op("uuid_ops")),
	index("memory_relationship_to_entity_idx").using("btree", table.toEntityId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "memory_relationship_anchor_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.fromEntityId],
			foreignColumns: [memoryEntity.id],
			name: "memory_relationship_from_entity_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.toEntityId],
			foreignColumns: [memoryEntity.id],
			name: "memory_relationship_to_entity_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("memory_relationship_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("memory_relationship_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("memory_relationship_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("memory_relationship_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const diaryEntry = pgTable("diary_entry", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	title: text(),
	body: text().notNull(),
	entryDate: date("entry_date"),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
	// TODO: failed to parse database type 'tsvector'
	bodyTsv: tsvector("body_tsv"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("diary_entry_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("date_ops"), table.entryDate.desc().nullsFirst().op("date_ops")),
	index("diary_entry_body_tsv_idx").using("gin", table.bodyTsv.asc().nullsLast().op("tsvector_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "diary_entry_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("diary_entry_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("diary_entry_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("diary_entry_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("diary_entry_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const calendarEvent = pgTable("calendar_event", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	googleEventId: text("google_event_id"),
	summary: text(),
	description: text(),
	startsAt: timestamp("starts_at", { withTimezone: true, mode: 'string' }),
	endsAt: timestamp("ends_at", { withTimezone: true, mode: 'string' }),
	location: text(),
	status: text().default('confirmed').notNull(),
	raw: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("calendar_event_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops"), table.startsAt.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "calendar_event_anchor_user_id_fkey"
		}).onDelete("cascade"),
	unique("calendar_event_anchor_user_id_google_event_id_key").on(table.anchorUserId, table.googleEventId),
	pgPolicy("calendar_event_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("calendar_event_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("calendar_event_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("calendar_event_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const memoryIndexItem = pgTable("memory_index_item", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	sourceKind: memorySourceKind("source_kind").notNull(),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	recallExcludedAt: timestamp("recall_excluded_at", { withTimezone: true, mode: 'string' }),
	conversationTranscriptId: uuid("conversation_transcript_id"),
	diaryEntryId: uuid("diary_entry_id"),
	memoryFactId: uuid("memory_fact_id"),
	calendarEventId: uuid("calendar_event_id"),
	embedding: vector({ dimensions: 1536 }),
	contentExcerpt: text("content_excerpt"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("memory_index_item_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("timestamptz_ops"), table.occurredAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "memory_index_item_anchor_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.conversationTranscriptId],
			foreignColumns: [conversationTranscript.id],
			name: "memory_index_item_conversation_transcript_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.diaryEntryId],
			foreignColumns: [diaryEntry.id],
			name: "memory_index_item_diary_entry_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.memoryFactId],
			foreignColumns: [memoryFact.id],
			name: "memory_index_item_memory_fact_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.calendarEventId],
			foreignColumns: [calendarEvent.id],
			name: "memory_index_item_calendar_event_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("memory_index_item_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("memory_index_item_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("memory_index_item_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("memory_index_item_sel", { as: "permissive", for: "select", to: ["public"] }),
	check("memory_index_item_single_source", sql`((((((conversation_transcript_id IS NOT NULL))::integer + ((diary_entry_id IS NOT NULL))::integer) + ((memory_fact_id IS NOT NULL))::integer) + ((calendar_event_id IS NOT NULL))::integer) = 1) AND (((source_kind = 'conversation_transcript'::memory_source_kind) AND (conversation_transcript_id IS NOT NULL)) OR ((source_kind = 'diary_entry'::memory_source_kind) AND (diary_entry_id IS NOT NULL)) OR ((source_kind = 'memory_fact'::memory_source_kind) AND (memory_fact_id IS NOT NULL)) OR ((source_kind = 'calendar_event'::memory_source_kind) AND (calendar_event_id IS NOT NULL)))`),
]);

export const trustedContact = pgTable("trusted_contact", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	displayName: text("display_name").notNull(),
	contactEmail: text("contact_email").notNull(),
	verificationState: trustedContactState("verification_state").default('pending').notNull(),
	verificationTokenHash: text("verification_token_hash"),
	verifiedAt: timestamp("verified_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("trusted_contact_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "trusted_contact_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("trusted_contact_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("trusted_contact_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("trusted_contact_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("trusted_contact_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const telegramSession = pgTable("telegram_session", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramUserId: bigint("telegram_user_id", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramChatId: bigint("telegram_chat_id", { mode: "number" }),
	metadata: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("telegram_session_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	index("telegram_session_telegram_user_id_idx").using("btree", table.telegramUserId.asc().nullsLast().op("int8_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "telegram_session_anchor_user_id_fkey"
		}).onDelete("cascade"),
	unique("telegram_session_anchor_user_id_telegram_user_id_key").on(table.anchorUserId, table.telegramUserId),
	pgPolicy("telegram_session_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("telegram_session_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("telegram_session_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("telegram_session_sel", { as: "permissive", for: "select", to: ["public"] }),
]);

export const appConfig = pgTable("app_config", {
	key: text().primaryKey().notNull(),
	value: text(),
	env: text(),
});

export const stripeEventLog = pgTable("stripe_event_log", {
	id: text().primaryKey().notNull(),
	payload: jsonb(),
	processedAt: timestamp("processed_at", { withTimezone: true, mode: 'string' }).defaultNow(),
});

export const auditEvent = pgTable("audit_event", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id"),
	eventType: text("event_type").notNull(),
	payload: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("audit_event_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("uuid_ops")),
	index("audit_event_event_type_idx").using("btree", table.eventType.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("text_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "audit_event_anchor_user_id_fkey"
		}).onDelete("set null"),
]);

export const agentCostLog = pgTable("agent_cost_log", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	anchorUserId: uuid("anchor_user_id"),
	model: text(),
	promptTokens: integer("prompt_tokens"),
	completionTokens: integer("completion_tokens"),
	totalTokens: integer("total_tokens"),
	costUsd: numeric("cost_usd", { precision: 12, scale:  6 }),
	occurredAt: timestamp("occurred_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	metadata: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("agent_cost_log_anchor_user_id_idx").using("btree", table.anchorUserId.asc().nullsLast().op("timestamptz_ops"), table.occurredAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "agent_cost_log_anchor_user_id_fkey"
		}).onDelete("set null"),
]);

export const anchorUser = pgTable("anchor_user", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	timezone: text().notNull(),
	locale: text().default('de').notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	telegramUserId: bigint("telegram_user_id", { mode: "number" }),
	stripeCustomerId: text("stripe_customer_id"),
	birthdateHash: text("birthdate_hash"),
	emailBouncedAt: timestamp("email_bounced_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.id],
			foreignColumns: [usersInAuth.id],
			name: "anchor_user_id_fkey"
		}).onDelete("cascade"),
	unique("anchor_user_telegram_user_id_key").on(table.telegramUserId),
	pgPolicy("anchor_user_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = id)` }),
	pgPolicy("anchor_user_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("anchor_user_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("anchor_user_sel", { as: "permissive", for: "select", to: ["public"] }),
	check("anchor_user_locale_check", sql`locale = ANY (ARRAY['de'::text, 'en'::text])`),
]);

export const anchorUserPlan = pgTable("anchor_user_plan", {
	anchorUserId: uuid("anchor_user_id").primaryKey().notNull(),
	plan: text().default('free').notNull(),
	stripeSubscriptionId: text("stripe_subscription_id"),
	currentPeriodEnd: timestamp("current_period_end", { withTimezone: true, mode: 'string' }),
	cancelAtPeriodEnd: boolean("cancel_at_period_end").default(false).notNull(),
	paymentFailedAt: timestamp("payment_failed_at", { withTimezone: true, mode: 'string' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "anchor_user_plan_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("anchor_user_plan_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("anchor_user_plan_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("anchor_user_plan_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("anchor_user_plan_sel", { as: "permissive", for: "select", to: ["public"] }),
	check("anchor_user_plan_plan_check", sql`plan = ANY (ARRAY['free'::text, 'pro'::text])`),
]);

export const googleConnection = pgTable("google_connection", {
	anchorUserId: uuid("anchor_user_id").primaryKey().notNull(),
	// TODO: failed to parse database type 'bytea'
	refreshTokenEncrypted: bytea("refresh_token_encrypted"),
	connectionState: googleConnectionState("connection_state").default('connected').notNull(),
	scope: text().default('https://www.googleapis.com/auth/calendar.events').notNull(),
	googleAccountEmail: text("google_account_email"),
	lastSyncedAt: timestamp("last_synced_at", { withTimezone: true, mode: 'string' }),
	disconnectedAt: timestamp("disconnected_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.anchorUserId],
			foreignColumns: [anchorUser.id],
			name: "google_connection_anchor_user_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("google_connection_del", { as: "permissive", for: "delete", to: ["public"], using: sql`(auth.uid() = anchor_user_id)` }),
	pgPolicy("google_connection_upd", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("google_connection_ins", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("google_connection_sel", { as: "permissive", for: "select", to: ["public"] }),
]);
