// GENERATED by drizzle-kit pull — do not hand-edit.
//
// This file is OVERWRITTEN by `pnpm drizzle-kit pull`, which introspects the live schema applied
// from supabase/migrations/*.sql (the source of truth, DEC-0013 / Pitfall 2). The pull emits the
// `pgTable` definitions for anchor_user, pairing_code, anchor_user_plan, memory_index_item,
// google_connection, etc. Never author tables here and never run `drizzle-kit generate`/`push`.
//
// Placeholder until the schema-freeze apply + pull runs (plan 00-03, Task 3).

export {};
